swagger: '2.0'
info:
  description: >-
   Servicio REST que invoca al servicio GDD y entrega la respuesta en formato JSON con las fechas recibidas y las fechas faltantes.
  version: 1.0.0
  title: API desafio uno Nivel 3
  contact:
    email: oronozp@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '127.0.0.1:8084'
basePath: /periodos
tags:
  - name: periodos
    description: Lista de periodos a procesar
schemes:
  - http
paths:
  /api:
    get:
      tags:
        - periodos
      summary: Lista de periodos a procesar
      operationId: periodos
      produces:
        - application/json
      responses:         
        '200':
          description: Periodo y lista de fechas
          schema:
            $ref: '#/definitions/Periodo'
definitions:
  Periodo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      fechaCreacion:
        type: string
        format: date
      fechaFin:
        type: string
        format: date
      fechas:
        type: array
        items:
          type: string
          format: date
      fechasFaltantes:
        type: array
        items:
          type: string
          format: date          
externalDocs:
  description: Especificación de swagger
  url: 'https://swagger.io/docs/specification/about/'